### PR TITLE
RU translation

### PR DESCRIPTION
**Pull request by Nickoriginal**
Prepare strings for new translation

### CODE REVIEW

**Comment by CodeDead** [comment]
Thank you @Nickoriginal !

I'll check the translations and merge this request if everything is in order.

In regards to crediting your work, would you like to be added to the credits list of the application and if so under what name and do you want a URL to be displayed as well?

**Comment by CodeDead** [comment]
In addition, I'm going to merge this with the `development` branch in accordance with git-flow.

**Comment by Nickoriginal** [comment]
Yes, I think your idea is good. I am happy to use my nick currently, so I think it is enough for mentioning me.
About the URL: I do not have website or blog, but you can insert my [GitHub](https://github.com/Nickoriginal) profile link.
Thank you for your work!

**Comment by CodeDead** [comment]
I should be the one thanking you for work!

**Pull request merged**
